apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ibm-anagrams-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1Gi
    requests:
      storage: 1Gi
  storageClassName: gp2
